[package]
name = "ddstats-rust"
version = "0.4.6"
authors = ["lsaa"]
edition = "2018"

[dependencies]
process-memory = "0.4.0"
sysinfo = "0.15.1"
winapi = "0.3.9"
tui = "0.10"
termion = "1.5.5"
serde_json = "1.0"
simple-logging = "2.0.2"
log = "0.4.11"