[package]
name = "ddstats-rust"
version = "0.6.8"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
process-memory = "0.4.0"
sysinfo = "0.15.1"
tonic = "0.5.2"
prost = "0.8"
tui = { version = "0.16.0", default-features = false, features = ["crossterm", "serde"]}
crossterm = "0.20.0"
ron = "0.6.4"
serde = { version = "1.0.60", features = ["serde_derive"] }
log = "0.4.14"
simple-logging = "2.0.2"
regex = "1.5.4"
scan_fmt = "0.2.6"

[build-dependencies]
tonic-build = { version = "0.5.2", features = ["prost"] }

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["tlhelp32"]}
