[package]
name = "ddstats-rust"
version = "0.4.6"
authors = ["lsaa"]
edition = "2018"

[dependencies]
process-memory = "0.4.0"
sysinfo = "0.15.1"
winapi = "0.3.9"
tui = "0.10"
termion = "1.5.5"
simple-logging = "2.0.2"
log = "0.4.11"
socketio-rust-emitter = "0.1.2"
confy = "0.4.0"
serde = "1.0.115"
serde_json = "1.0.57"
serde_derive = "1.0.115"
clipboard = "0.5.0"
isahc = { version = "0.9.8", features=["json"] }
md5 = "0.7.0"