cargo-features = ["strip"]

[package]
name = "ddstats-rust"
version = "0.6.8"
edition = "2018"

[profile.release]
strip = true
lto = true
codegen-units = 1

[dependencies]
process-memory = "0.4.0"
sysinfo = "0.15.1"
tonic = "0.5.2"
prost = "0.8"
tui = { version = "0.16.0", default-features = false, features = ["crossterm", "serde"]}
crossterm = "0.20.0"
ron = "0.6.4"
serde = { version = "1.0.60", features = ["serde_derive"] }
serde_json = "1.0"
log = "0.4.14"
simple-logging = "2.0.2"
regex = "1.5.4"
scan_fmt = "0.2.6"
futures = "0.3.17"
tokio = { version = "1.11.0", default-features = false, features = ["rt-multi-thread", "macros", "sync"] }
tokio-stream = { version = "0.1.7", features = ["net"] }
log-panics = "2.0.0"
num-traits = "0.2"
num-derive = "0.2"
spin_sleep = "1.0.0"
warp = "0.3.1"

[build-dependencies]
tonic-build = { version = "0.5.2", features = ["prost"] }

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["tlhelp32"]}
