cargo-features = ["strip"]

[package]
name = "ddstats-rust"
version = "0.6.9"
edition = "2021"

[profile.release]
strip = true
lto = true
codegen-units = 1

[dependencies]
ddcore-rs = { version = "0.1.4", features = ["memory", "ddinfo", "ddcl_submit"] }
tonic = "0.5.2"
prost = "0.8"
tui = { version = "0.16.0", default-features = false, features = ["crossterm", "serde"]}
crossterm = "0.20.0"
ron = "0.6.4"
serde = { version = "1.0.60", features = ["serde_derive"] }
serde_json = "1.0"
log = "0.4.14"
simple-logging = "2.0.2"
regex = "1.5.4"
futures = "0.3.17"
tokio = { version = "1.11.0", default-features = false, features = ["full"] }
tokio-stream = { version = "0.1.7", features = ["net"] }
log-panics = "2.0.0"
num-traits = "0.2"
num-derive = "0.2"
hyper = "0.14.12"
hyper-tls = { version = "0.5.0" }
warp = "0.3.1"
lazy_static = "1.4.0"
clipboard = "0.5.0"
native-tls = "0.2.8"
websocket = "0.26.2"
anyhow = "1.0.43"

[build-dependencies]
tonic-build = { version = "0.5.2", features = ["prost"] }
