[package]
name = "ddstats-rust"
version = "0.1.0"
authors = ["lsaa"]
edition = "2018"

[dependencies]
process-memory = "0.4.0"
sysinfo = "0.15.1"
winapi = "0.3.9"
tui = "0.10"
termion = "1.5.5"
clokwerk = "0.3.3"