host = 'https://ddstats.com'
offline = false
auto_clipboard = true

[stream]
stats = true
replay_stats = true
non_default_spawnsets = true

[submit]
stats = true
replay_stats = true
non_default_spawnsets = true

[discord]
notify_above_1000 = true
notify_player_best = true
notify_custom_spawnsets = false
