name: Rust

on:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-release:
    name: Build & Release
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - name: Build (x86_64-unknown-linux-musl)
        run: |
          docker build -t cross-rust-linux docker/linux
          docker run --rm -v "$(pwd)":/src cross-rust-linux --user $(id -u):$(id -g)
      - name: Archive compiled data
        uses: actions/upload-artifact@v4
        with:
          name: ddstats-rust-linux
          path: target/x86_64-unknown-linux-gnu/release/ddstats-rust
      - name: Package
        run: sh .github/workflows/package.sh
      - uses: ncipollo/release-action@v1
        with:
          commit: main
          tag: v0.6.10-${{ github.run_number }}
          artifacts: "ddstats-rust-linux-x86_64.zip,ddstats-rust-windows-x86_64.zip"
          preRelease: false
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}
