name: Rust

on:
  pull_request:
    branches: [master]
    types: ['ready_for_review']

env:
  CARGO_TERM_COLOR: always

jobs:
  build-release:
    name: Build & Release
    runs-on: ubuntu-latest
    environment: DDCL
    steps:
      - uses: actions/checkout@v2
      - name: Un-Mold
        run: rm -r .cargo
      - name: Setup Docker (Linux)
        run: docker build -t cross-rust-linux docker/linux
      - name: Setup Docker (Windows)
        run: docker build -t cross-rust-windows docker/windows
      - name: Install latest rust
        uses: actions-rs/toolchain@v1
        with:
            target: x86_64-unknown-linux-gnu
            toolchain: nightly
            override: true
            components: rustfmt, clippy
      - name: Install latest rust (windows)
        uses: actions-rs/toolchain@v1
        with:
            target: x86_64-pc-windows-gnu
            toolchain: nightly
            override: true
            components: rustfmt, clippy
      - uses: actions-rs/cargo@v1
        env:
          DDCL_SECRETS_IV: ${{ secrets.DDCL_SECRETS_IV }}
          DDCL_SECRETS_SALT: ${{ secrets.DDCL_SECRETS_SALT }}
          DDCL_SECRETS_PASS: ${{ secrets.DDCL_SECRETS_PASS }}
        with:
          use-cross: true
          command: build
          args: --release --target=x86_64-unknown-linux-gnu
      - uses: actions-rs/cargo@v1
        env:
          DDCL_SECRETS_IV: ${{ secrets.DDCL_SECRETS_IV }}
          DDCL_SECRETS_SALT: ${{ secrets.DDCL_SECRETS_SALT }}
          DDCL_SECRETS_PASS: ${{ secrets.DDCL_SECRETS_PASS }}
        with:
          use-cross: true
          command: build
          args: --release --target=x86_64-pc-windows-gnu
      - name: Archive compiled data
        uses: actions/upload-artifact@v2
        with:
          name: ddstats-rust-linux
          path: target/x86_64-unknown-linux-gnu/release/ddstats-rust
      - name: Archive compiled data (windows)
        uses: actions/upload-artifact@v2
        with:
          name: ddstats-rust-windows
          path: target/x86_64-pc-windows-gnu/release/ddstats-rust.exe
      - name: Package
        run: sh .github/workflows/package.sh
      - uses: ncipollo/release-action@v1
        with:
          commit: master
          tag: v0.6.10-${{ github.run_number }}
          artifacts: "ddstats-rust-linux-x86_64.zip,ddstats-rust-windows-x86_64.zip"
          preRelease: false
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}
