name: Rust

on:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-release:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest rust
        uses: actions-rs/toolchain@v1
        with:
            target: x86_64-unknown-linux-gnu
            toolchain: nightly
            override: true
            components: rustfmt, clippy
      - name: Install latest cross
        run: cargo install cross
      - name: Install openssl and deps
        run: apt-get install libx11-xcb-dev libgl1-mesa-dev xorg-dev openssl libssl-dev pkg-config python3
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=x86_64-unknown-linux-gnu
      - name: Archive compiled data
        uses: actions/upload-artifact@v4
        with:
          name: ddstats-rust-linux
          path: target/x86_64-unknown-linux-gnu/release/ddstats-rust
      - name: Package
        run: sh .github/workflows/package.sh
      - uses: ncipollo/release-action@v1
        with:
          commit: main
          tag: v0.6.10-${{ github.run_number }}
          artifacts: "ddstats-rust-linux-x86_64.zip,ddstats-rust-windows-x86_64.zip"
          preRelease: false
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}
